global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["vps:9100", "raspberry:9100"]

remote_write:
  - url: "<Your Prometheus in Grafana cloud remote_write endpoint>"
    basic_auth:
      username: "<Your Prometheus in Grafana cloud Username>"
      password: "<Your Prometheus in Grafana cloud API key>"
