services:
  bot:
    image: control_unit_bot:dev
    platform: ${PLATFORM}
    network_mode: bridge
    ports:
      - "8000:8000"

  # just a mock
  wireguard:
    image: linuxserver/wireguard
    profiles:
      - skip
