version: "3.9"

services:
  bot:
    build:
      dockerfile: docker/Dockerfile
    network_mode: bridge
    ports:
      - "8000:8000"

  # just a mock
  wireguard:
    image: linuxserver/wireguard
    profiles:
      - skip
